[WebGPU EP] Remove unused variable. (#22412)
### Description
<!-- Describe your changes. -->

Remove unused variable.

### Motivation and Context
<!-- - Why is this change required? What problem does it solve?
- If it fixes an open issue, please link to the issue here. -->

Fix Android build error:

```
onnxruntime/onnxruntime/core/providers/webgpu/webgpu_context.h:122:12: error: private field 'query_time_base_' is not used [-Werror,-Wunused-private-field]
  122 |   uint64_t query_time_base_;
      |            ^
1 error generated.
```