Merged PR 5578: Include math.h
If you try to build from scratch, at least with g++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0, you get this error:

```
onnxruntime/orttraining/orttraining/core/graph/gradient_schema_defs.cc:870:95: error: ‘M_2_SQRTPI’ was not declared in this scope
            ONNX_NAMESPACE::FunctionBodyHelper::Const<float>("Two_sqrt_pi", static_cast<float>(M_2_SQRTPI)),
```

‘M_2_SQRTPI’ defined in math.h, which is never included from gradient_schema_defs.cc even indirectly.