Fix globalThis property missing
test/test-main.ts:18:12 - error TS2339: Property 'Float16Array' does not exist on type 'typeof globalThis'.

18 globalThis.Float16Array = Float16Array;