Suppress GCC warning in TreeEnsembleAggregator
When building with GCC 14.2.1, I got the following warning:

onnxruntime/core/providers/cpu/ml/tree_ensemble_aggregator.h:329:59: error: template-id not allowed for constructor in C++20 [-Werror=template-id-cdtor]

Remove template parameters from the constructor: The constructor
TreeAggregatorMax<InputType, ThresholdType, OutputType>
has been simplified to TreeAggregatorMax, because the compiler
already knows the template parameters from the class definition.

Signed-off-by: Clément Péron <peron.clem@gmail.com>