[CMake] Enable NCCL only when enabling CUDA support
Conditionally enable NCCL depending on the --enable_cuda
flag.

Before this change NCCL support was enabled unconditionally, even
when building without CUDA support.
This caused the command:
`$ ./build.sh --enable_training`
to fail for me with the following error:
`/usr/include/nccl.h:10:10: fatal error: cuda_runtime.h: No such file or
directory`

This is because the file:
`orttraining/orttraining/models/runner/training_runner.cc`
would include nccl without adding the CUDA includes.

No changes to the build command should be needed.