Fix WebGPU build error when LTO is enabled (#32813)
### Description
<!-- Describe your changes. -->
Fix warning from recent change in #32729

> LINK : error C2220: the following warning is treated as an error
[N:\_work\1\b\RelWithDebInfo\onnxruntime_provider_test.vcxproj]
LINK : warning C4744: 'static char const
absl::lts_20250814::base_internal::FastTypeTag<class
std::basic_string<char,struct std::char_traits<char>,class
std::allocator<char> > >::kDummyVar' has different type in
'n:\_work\1\b\relwithdebinfo\_deps\googletest-src\googletest\src\gtest-all.cc'
and
'n:\_work\1\s\onnxruntime\test\providers\webgpu\webgpu_context_test.cc':
'unsigned char' and 'signed char'
[N:\_work\1\b\RelWithDebInfo\onnxruntime_provider_test.vcxproj]


### Motivation and Context
<!-- - Why is this change required? What problem does it solve?
- If it fixes an open issue, please link to the issue here. -->
Fix packaging pipeline