Merged PR 5157: Fix missing math header for training_util.h
Scanning dependencies of target onnxruntime_test_all
[ 79%] Building CXX object CMakeFiles/onnxruntime_test_all.dir/home/thiagofc/dev/vsts/onnxruntime/onnxruntime/test/training_test/gradient_graph_builder_test.cc.o
In file included from /home/thiagofc/dev/vsts/onnxruntime/onnxruntime/test/training/runner/data_loader.h:15:0,
                 from /home/thiagofc/dev/vsts/onnxruntime/onnxruntime/test/training/runner/training_runner.h:13,
                 from /home/thiagofc/dev/vsts/onnxruntime/onnxruntime/test/training_test/gradient_graph_builder_test.cc:8:
/home/thiagofc/dev/vsts/onnxruntime/onnxruntime/test/training/runner/training_util.h:6:10: fatal error: math: No such file or directory
 #include <math>
          ^~~~~~
compilation terminated.
CMakeFiles/onnxruntime_test_all.dir/build.make:2103: recipe for target 'CMakeFiles/onnxruntime_test_all.dir/home/thiagofc/dev/vsts/onnxruntime/onnxruntime/test/training_test/gradient_graph_builder_test.cc.o' failed
make[2]: *** [CMakeFiles/onnxruntime_test_all.dir/home/thiagofc/dev/vsts/onnxruntime/onnxruntime/test/training_test/gradient_graph_builder_test.cc.o] Error 1
CMakeFiles/Makefile2:469: recipe for target 'CMakeFiles/onnxruntime_test_all.dir/all' failed
make[1]: *** [CMakeFiles/onnxruntime_test_all.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2