Fix bert_toy_fetches.h compiling with clang
In some version of clang (ROCm hip-clang is using), we got:
> fatal error: instantiating fold expression with 16383 arguments exceeded expression nesting limit of 256

By eliminating the trailing zeros, the errors will be fixed, so we switch to explicitly set the
array size and relay on the fact that this global variable has static storage duration and then
all those remaining elements will be zero initialized.