Fix compile issue in Azure EP unit test (#24446)
### Description
Fix compilation issue (undeclared identifier) in Azure EP unit test.



### Motivation and Context
A previous PR caused a compilation issue in the Azure EP unit test:
https://github.com/microsoft/onnxruntime/pull/24433

Our PR CI pipelines did not catch it. It was caught by our post-merge
packaging pipelines.

```shell
D:\a\_work\1\s\onnxruntime\test\providers\azure\azure_basic_test.cc(28,3): error C2065: 'session_options': undeclared identifier [D:\a\_work\1\b\RelWithDebInfo\onnxruntime_test_all.vcxproj]
D:\a\_work\1\s\onnxruntime\test\providers\azure\azure_basic_test.cc(29,3): error C2065: 'session_options': undeclared identifier [D:\a\_work\1\b\RelWithDebInfo\onnxruntime_test_all.vcxproj]
D:\a\_work\1\s\onnxruntime\test\providers\azure\azure_basic_test.cc(30,3): error C2065: 'session_options': undeclared identifier [D:\a\_work\1\b\RelWithDebInfo\onnxruntime_test_all.vcxproj]
```