fix printDebugInfo in ov_interface.cc (#25298)
error C2181: illegal else without matching if

Fix compilation in debug due to {} mismatch

---------

Co-authored-by: Julien Maille <julien.maille@data-pixel.com>