[NvTensorRTRTX EP]: Add missing override specifiers to suppress warnings (#27288)
### Description
<!-- Describe your changes. -->

Compilation on Clang toolchains on Linux currently fails due to this
warning (among others) since ONNX runtime compiles with -Werror by
default. We address `-Winconsistent-missing-override` with this PR in
TRT NV EP.

```
/home/stephan/projects/onnxruntime-winai/onnxruntime/core/providers/nv_tensorrt_rtx/nv_execution_provider.h:309:7: error: 'GetDeviceId' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
  309 |   int GetDeviceId() const { return device_id_; }
      |       ^
/home/stephan/projects/onnxruntime-winai/include/onnxruntime/core/framework/execution_provider.h:183:15: note: overridden virtual function is here
  183 |   virtual int GetDeviceId() const { return default_device_.Id(); }
      |               ^
In file included from /home/stephan/projects/onnxruntime-winai/onnxruntime/core/providers/nv_tensorrt_rtx/nv_provider_factory.cc:18:
/home/stephan/projects/onnxruntime-winai/onnxruntime/core/providers/nv_tensorrt_rtx/nv_execution_provider.h:310:10: error: 'Sync' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
  310 |   Status Sync() const;
      |          ^
/home/stephan/projects/onnxruntime-winai/include/onnxruntime/core/framework/execution_provider.h:231:26: note: overridden virtual function is here
  231 |   virtual common::Status Sync() const { return Status::OK(); }
      |                          ^
/home/stephan/projects/onnxruntime-winai/onnxruntime/core/providers/nv_tensorrt_rtx/nv_provider_factory.cc:63:39: error: 'CreateProvider' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
   63 |   std::unique_ptr<IExecutionProvider> CreateProvider(const OrtSessionOptions& session_options,
      |                                       ^
/home/stephan/projects/onnxruntime-winai/include/onnxruntime/core/providers/providers.h:29:47: note: overridden virtual function is here
   29 |   virtual std::unique_ptr<IExecutionProvider> CreateProvider(const OrtSessionOptions& session_options,
      |                                               ^
/home/stephan/projects/onnxruntime-winai/onnxruntime/core/providers/nv_tensorrt_rtx/nv_provider_factory.cc:112:46: error: 'CreateExecutionProviderFactory' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
  112 |   std::shared_ptr<IExecutionProviderFactory> CreateExecutionProviderFactory(const void* param) {
      |                                              ^
/home/stephan/projects/onnxruntime-winai/onnxruntime/core/providers/shared_library/provider_host_api.h:19:54: note: overridden virtual function is here
   19 |   virtual std::shared_ptr<IExecutionProviderFactory> CreateExecutionProviderFactory(const void* /*provider_options*/) { return nullptr;
/home/stephan/projects/onnxruntime-winai/onnxruntime/core/providers/nv_tensorrt_rtx/nv_execution_provider.h:309:7: error: 'GetDeviceId' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
  309 |   int GetDeviceId() const { return device_id_; }
      |       ^
/home/stephan/projects/onnxruntime-winai/include/onnxruntime/core/framework/execution_provider.h:183:15: note: overridden virtual function is here
  183 |   virtual int GetDeviceId() const { return default_device_.Id(); }
```

### Motivation and Context
<!-- - Why is this change required? What problem does it solve?
- If it fixes an open issue, please link to the issue here. -->

Fixing clang warnings enables builds with clang on Linux since `-Werror`
enforces warning-free builds.